### ISSUE TITLE
Signatures should be dynamically pulled from user profile data

### ISSUE THREAD

**Issue by ProjectThreepio** [jaysylvester/comitium#142]
At the moment, it appears if a post contains a signature, that signature doesn't get updated when the user updates their signature.  This can create scenarios where the information in the signatures in old posts is outdated or badly formatted, and cannot be fixed.

**Comment by jaysylvester** [comment]
Signatures are stored in the cache along with posts when a topic is first requested. When a user updates their signature, changes are reflected when the topic cache expires (either when the topic receives a reply and the cache is refreshed or the cache expires on its own). Clearing the topic cache just because a user updates their signature would require that all topics containing posts from that user would need to be refreshed (database heavy).

Signatures could theoretically be requested separately, but this would entail an additional database call and I don't think it's worth the performance cost.

**Comment by ProjectThreepio** [comment]
Ah, OK.  So signatures don't last forever--that was my main worry.
A secondary issue is trying to do potentially difficult formatting without any feedback of what the signature actually looks like.  That might be doable in a future version of the signature editor in the user profile.

**Comment by ProjectThreepio** [comment]
Actually this last point would probably be fixed by an advanced editor of some sort, so assuming the same editor used for posting would be used for editing signatures, then this whole bug could be marked as a dupe and closed.

**Comment by ProjectThreepio** [comment]
Yeah, I'm going to close this out--it's really an advanced editor dupe bug.
