### ISSUE TITLE
Ignore most, if not all, of @jayslayers suggestions for changing the PM system.

### ISSUE THREAD

**Issue by Danfun64** [jaysylvester/comitium#5]
This issue is about #2, #3, and to a lesser extent #1.

The way PM's are set-up on originaltrilogy.com is not unlike how PM's are handled in other forums. PM's aren't threads, in a way they are more like emails.

@jaysylvester wants a total overhaul of the PM system to make it something other than PMing. I'm not sure this is wise. #1 is the only suggestion that I think makes sense. Maybe PM's should be more email like, with both a "To" and a "Cc". #2 and especially #3 are just plain weird and make PM's more thread like, which they aren't.

This is what I suggest, and it doesn't have to be followed. It would be nice, though.

**Comment by jaysylvester** [comment]
I don't think the author of the software is going to be ignoring his own feature suggestions.

Yes, PMs are more like e-mail. Really crappy, limited e-mail, which is also limited in its own ways. I don't see why that's a great model to follow. How old is the concept of PMs, like 20 years? I think we can do better.

If you want to use private topics like old school private messages, there's nothing stopping you. Enter a recipient's name (or click a link in their profile), type a message, hit submit. They'll receive a notification via e-mail. They respond. You receive a notification e-mail. You respond. The only difference is that you'll see the conversation as a stream of messages—something available in all modern e-mail clients, though a bit clumsier in their implementation because they have to guess what messages belong in what conversations. The ability to view an entire PM conversation is a very old feature request from users, actually. Private topics provide that, and much more.

Let's continue with comparing PMs to e-mails. How annoying and error-prone are Cc and Bcc fields? Answer: very. Who's on this message? Did I get everyone? Am I sending it to someone I don't intend? Given these problems, why follow this model in 2015?

Private topics have all participants clearly listed at the top of the conversation. If you post a message to that conversation, you know exactly who's getting it. If you want to speak to someone else individually, you start a new private topic, which, again, is just like sending a private message.

These features are already largely implemented. I put them in here more as reminders than anything. Users will have the opportunity to test and evaluate the new private topic system. I think most will prefer it to traditional private messages.

**Comment by Danfun64** [comment]
"I don't think the author of the software is going to be ignoring his own feature suggestions."

You're probably right xD. Thread-like PM's still seem a weird idea to me though :P
